version: 2.1
jobs:
  build-development:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'f6c:20:53:fc:7a:da:9f:5f:72:f2:06:a5:d1:a8:41:c0'
      - run:
          name: Deploy app to server development
          command: |
            ssh -o StrictHostKeyChecking=no admindevops@128.199.75.235 "cd /var/www/html/api-dpatriod-resto && ./deploy.sh"
workflows :
  basic-workflow:
    jobs:
      - build-development:
          filters:
            branches:
              only:
                - main
